### ISSUE TITLE
یه سوال

### ISSUE THREAD

**Issue by mimsadAlef** [font-store/BinamaFont#1]
آیا مبلغ دونیت تغییری نکرده؟
یعنی با همان 20 هزار تومن نسخه فونت رو می دید؟😁

**Comment by mimsadAlef** [comment]
جواب سوالم رو پیدا کردم سوال بعدی الان چند درصد از حمایت ها انجام شده است🧐

**Comment by mimsadAlef** [comment]
@zoghal

**Comment by zoghal** [comment]
سلام آره عزیزجان
تورم روش تاثیری نذاشته :))
